### ISSUE TITLE
Weird error...

### ISSUE THREAD

**Issue by SamHep0803** [EthanC/Sleuth#3]
Don't know what this is, wondering of you could help.

```
Traceback (most recent call last):
  File "newsfeed.py", line 174, in <module>
    Sleuth.main(Sleuth)
  File "newsfeed.py", line 34, in main
    diff = Sleuth.Diff(self, news)
  File "newsfeed.py", line 82, in Diff
    oldNews = json.loads(Utility.ReadFile(self, "news", "json", "data/"))
  File "C:\Users\Samue\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Samue\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Samue\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by EthanC** [comment]
Try deleting your data/news.json file and re-running the script, let me know how that goes.

**Comment by innowebka** [comment]
File "newsfeed.py", line 108
    elif (_title := motd.get("title")) in self.ignoredTitles:
                 ^
SyntaxError: invalid syntax

**how to fix this error ?**
